### ISSUE TITLE
how can i call python3 function in groutine

### ISSUE THREAD

**Issue by xxz199539** [go-python/cpy3#3]
![image](https://user-images.githubusercontent.com/38350849/147452972-6eb7da8d-51b7-49dc-a404-7861c0537714.png)
I get this error when i call py func in groutine

**Comment by MarSoft** [comment]
Try the following:
1. Lock your goroutine to the thread: `runtime.LockOSThread(); defer runtime.UnlockOSThread()` - to avoid it jumping between threads while python code is called
2. Make sure you acquire GIL in the coroutine's thread: `gilstate := py.PyGILState_Ensure(); defer py.PyGILState_Release(gilstate)` - so that GIL is acquired while you call Python code
3. Now you *should* be safe to call Python code.

I cannot tell more without seeing your code. A minimal reproducing example would be ideal.

**Comment by christian-korneck** [comment]
Quoting from a [previous issue](https://github.com/DataDog/go-python3/issues/49):

> This project is just a relatively thin wrapper around Python's C API. So basically all the limitations of the Python C API apply. One limitation is that Python has a global interpreter lock (GIL). You can't do multiple things in a Python interpreter at the same time (unless you use Python's concurrency features in the Python code that you're executing).
> 
> The easiest way to make embedded Python to work with goroutines is to make sure that only one goroutine is actually "doing" Python at a time and all the other ones have to wait. Here's an excellent [blog post](https://www.datadoghq.com/blog/engineering/cgo-and-python/#the-dreadful-global-interpreter-lock) and related [conference talk](https://www.youtube.com/watch?v=yrEi5ezq2-c) that cover this and a few other options.
